databases:
  - name: medic-api
    ipAllowList: []
    plan: free

services:
  - type: web
    name: rails
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh && bundle exec rails db:migrate RAILS_ENV=production"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medic-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      # - key: WEB_CONCURRENCY
      #   value: 2 # sensible default