# Exported from Render on 2024-10-06T15:18:47Z
databases:
- name: medic-api
  databaseName: postgres_wjjk
  user: postgres_wjjk_user
  plan: free
  region: oregon
  ipAllowList: []
  postgresMajorVersion: "16"
services:
- type: web
  name: rails
  runtime: ruby
  repo: https://github.com/HossainAraf/medic-api
  branch: handle-request
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: medic-api
      property: connectionString
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
