
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medic-api

test:
  <<: *default
  database: medic-api_test


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: medic-api
  password: <%= ENV["MEDIC_API_DATABASE_PASSWORD"] %>
