name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop -v '>= 1.0, < 2.0' # https://docs.rubocop.org/en/stable/installation/
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.rubocop.yml
      - name: Rubocop Report
        run: rubocop --color
      - name: Rubocop Autocorrect
        run: rubocop --color -a || true
        continue-on-error: true
      - name: Rubocop Report (after autocorrect)
        run: rubocop --color || true
        continue-on-error: true
      - name: Upload Rubocop Report
        uses: actions/upload-artifact@v4
        with:
          name: rubocop-report  
        